export default {
  bookmarks: {
    todo: "待办事宜",
    news: "消息动态",
    all_app: "全部应用"
  },
  todo: {
    things_done: "已办事宜",
    upcoming: '待办',
    done: '已办',
    delayed_submission: "延迟提交",
    ontime_submission: "按时提交",
    create: "创建",
    time_limit: "限时",
    time_out: "超时",
    year: '年',
    month: '月',
    day: '天',
  },
  news: {
    unread: "未读",
    readed: "已读",
    load_more: "点击加载更多",
    Loaded: "已加载完成",
    nodata: "暂无数据",
    read_all: "全部已读",
    just: "刚刚",
    minutes_ago: "分钟前",
    hours_ago: "小时前",
    days_ago: "天前",
    prompt: "提示",
    msg: "是否将未读信息全部置为已读？",
    cancel: "取消",
    confirm: "确认"
  },
  all_app: {
    app_center: "应用中心"
  },
  app_name:{
    "AI": "AI助手",
    "QDDK": "签到打卡",
    "WQQD": "外勤签到",
    "GGSQ": "公干申请",
    "TM": "考勤管理",
    "CT": "协作任务",
    "CP": "协作项目",
    "WF": "流程管理",
    "ADM": "行政管理",
    "CNT": "通讯录",
    "QA": "问卷管理",
    "TA": "人才管理",
    "TA_P": "员工点赞",
    "OM": "组织人事",
    "PM": "绩效管理",
    "KM": "知识管理",
    "EX": "实时激励",
    "RC": "招聘管理",
    "TR": "培训管理",
    "WR": "工作报告",
    "MC": "个人中心",
    "EC": "员工关怀",
    "TM_BW": "加班申请",
    "TM_BT": "出差申请",
    "TM_AL": "请假申请",
    "TM_ML": "考勤统计",
    "CL": "签到报表",
    "PA_RP": "智能报表",
    "KAIPIAO": "开票信息",
    "PT": "积分激励",
    "TP": "脱普大学",
    "undefined":""
  }
};
