export default {
  bookmarks: {
    todo: "To do",
    news: "News",
    all_app: "All applications"
  },
  todo: {
    things_done: "Things done",
    upcoming: 'Upcoming',
    done: 'Done',
    delayed_submission: "Delayed submission",
    ontime_submission: "Submit on time",
    create: "create",
    time_limit: "Time limit",
    time_out: "Time out",
    year: 'year',
    month: 'month',
    day: 'day',
  },
  news: {
    unread: "unread",
    readed: "Have read",
    load_more: "loading...",
    Loaded: "Loaded",
    nodata: "No data",
    read_all: "Read all",
    just: "just recently",
    minutes_ago: "Minutes ago",
    hours_ago: "Hours ago",
    days_ago: "Days ago",
    prompt: "prompt",
    msg: "Are all unread messages read?",
    cancel: "cancel",
    confirm: "confirm"
  },
  all_app: {
    app_center: "Application center"
  },
  app_name: {
    "AI": "AI assistant",
    "QDDK": "Sign-in",
    "WQQD": "Outside Sign-in",
    "GGSQ": "Application",
    "TM": "Attd",
    "CT": "Task",
    "CP": "Project",
    "WF": "Workflow",
    "ADM": "Admin",
    "CNT": "Contacts",
    "QA": "Questionnaire",
    "TA": "Talent",
    "TA_P": "Staff praise",
    "OM": "Organization",
    "PM": "performance",
    "KM": "Knowledge",
    "EX": "Incentive",
    "RC": "Recruitment",
    "TR": "Training",
    "WR": "Work",
    "MC": "Personal Center",
    "EC": "Staff Care",
    "TM_BW": "Overtime",
    "TM_BT": "Business Trip",
    "TM_AL": "Leave",
    "TM_ML": "Attd Stats",
    "CL": "Sign in report",
    "PA_RP": "Smart Report",
    "KAIPIAO": "Draw a Bill",
    "PT": "Points Incentive",
    "TP": "University of de Pu",
    "undefined": ""
  }
};
