export default {
  bookmarks: {
    todo: "To do",
    news: "News",
    all_app: "All applications"
  },
  todo: {
    things_done: "Things done",
    upcoming: 'Upcoming',
    done: 'Done',
    delayed_submission: "Delayed submission",
    create: "create",
    time_limit: "Time limit",
    time_out: "Time out",
    year: 'year',
    month: 'month',
    day: 'day',
  },
  news: {
    unread: "unread",
    readed: "Have read",
    load_more: "Click to load more",
    Loaded: "Loaded",
    nodata: "No data",
    read_all: "Read all",
    just: "just recently",
    minutes_ago: "Minutes ago",
    hours_ago: "Hours ago",
    days_ago: "Days ago",
    prompt: "prompt",
    msg: "Are all unread messages read?",
    cancel: "cancel",
    confirm: "confirm"
  },
  all_app: {
    app_center: "Application center"
  },
  app_name:{
    "AI": "AI assistant",
    "QDDK": "Daily attendance card",
    "WQQD": "Field attendance",
    "GGSQ": "Business application",
    "TM": "Attendance management",
    "CT": "Collaborative task",
    "CP": "joint-operated project",
    "WF": "Process management",
    "ADM": "Administrative management",
    "CNT": "Mail list",
    "QA": "Questionnaire management",
    "TA": "Talent management",
    "TA_P": "Staff praise",
    "OM": "Organization and personnel",
    "PM": "performance management",
    "KM": "knowledge management",
    "EX": "Real-time excitation",
    "RC": "Recruitment management",
    "TR": "Training management",
    "WR": "Work report",
    "MC": "Personal Center",
    "EC": "Employee care",
    "TM_BW": "Overtime application",
    "TM_BT": "Application for business trip",
    "TM_AL": "Leave request",
    "TM_ML": "Attendance statistics",
    "CL": "Sign in report",
    "PA_RP": "Intelligent report forms",
    "KAIPIAO": "Invoice information",
    "PT": "Integral excitation",
    "TP": "University of de Pu",
    "undefined":""
  }
};
